##  Importing Important Libraries 

In [1]:
import pandas as pd
import numpy as np

## Importing Dataset 

In [2]:
data1 = pd.read_csv('book.csv',sep=',')

In [3]:
data1.head()

Unnamed: 0  User.ID                                         Book.Title  \
0           1   276726                                Classical Mythology   
1           2   276729                                       Clara Callan   
2           3   276729                               Decision in Normandy   
3           4   276736  Flu: The Story of the Great Influenza Pandemic...   
4           5   276737                             The Mummies of Urumchi   

   Book.Rating  
0            5  
1            3  
2            6  
3            8  
4            6

## Initial Analysis

In [4]:
data1.isnull().sum()

Unnamed: 0     0
User.ID        0
Book.Title     0
Book.Rating    0
dtype: int64

In [5]:
data1.shape

(10000, 4)

In [6]:
data1['User.ID'].nunique()      # in total we have 2182 unique users 

2182

In [7]:
data1['Book.Title'].nunique()

9659

In [8]:
data1['Book.Title'].unique()

array(['Classical Mythology', 'Clara Callan', 'Decision in Normandy', ...,
       'How to Flirt: A Practical Guide', 'Twilight',
       'Kids Say the Darndest Things'], dtype=object)

## Data Preparation for Recommendation 

In [28]:
del data1['Unnamed: 0']

In [9]:
user_user_recommendation = pd.pivot_table(data=data1,index='User.ID',columns='Book.Title',values='Book.Rating').reset_index(drop=True)
user_user_recommendation.head()

Book.Title   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
0                            NaN                                         NaN   
1                            NaN                                         NaN   
2                            NaN                                         NaN   
3                            NaN                                         NaN   
4                            NaN                                         NaN   

Book.Title   Repairing PC Drives &amp  '48  \
0                                 NaN  NaN   
1                                 NaN  NaN   
2                                 NaN  NaN   
3                                 NaN  NaN   
4                                 NaN  NaN   

Book.Title  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
0                                                         NaN                       
1                                                         NaN                       
2                                                         NaN                       
3                                                         NaN                       
4                                                         NaN                       

Book.Title  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
0                                                         NaN              
1                                                         NaN              
2                                                         NaN              
3                                                         NaN              
4                                                         NaN              

Book.Title  01-01-00: A Novel of the Millennium  \
0                                           NaN   
1                                           NaN   
2                                           NaN   
3                                           NaN   
4                                           NaN   

Book.Title  1,401 More Things That P*Ss Me Off  10 Commandments Of Dating  \
0                                          NaN                        NaN   
1                                          NaN                        NaN   
2                                          NaN                        NaN   
3                                          NaN                        NaN   
4                                          NaN                        NaN   

Book.Title  100 Great Fantasy Short, Short Stories  ...  \
0                                              NaN  ...   
1                                              NaN  ...   
2                                              NaN  ...   
3                                              NaN  ...   
4                                              NaN  ...   

Book.Title  Zora Hurston and the Chinaberry Tree (Reading Rainbow Book)  \
0                                                         NaN             
1                                                         NaN             
2                                                         NaN             
3                                                         NaN             
4                                                         NaN             

Book.Title  \Even Monkeys Fall from Trees\ and Other Japanese Proverbs  \
0                                                         NaN            
1                                                         NaN            
2                                                         NaN            
3                                                         NaN            
4                                                         NaN            

Book.Title  \I Won't Learn from You\: And Other Thoughts on Creative Maladjustment  \
0                                                         NaN                        
1                                                         NaN                    

In [10]:
user_user_recommendation['Classical Mythology'].unique()

array([nan,  5.])

In [11]:
user_user_recommendation['Decision in Normandy'].unique()

array([nan,  6.])

In [12]:
user_user_recommendation.shape

(2182, 9659)

In [13]:
data1['User.ID'].unique()

array([276726, 276729, 276736, ..., 162113, 162121, 162129], dtype=int64)

In [14]:
data1['User.ID'].shape

(10000,)

In [15]:
user_user_recommendation.index = data1['User.ID'].unique()
user_user_recommendation.head(10)

Book.Title   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
276726                       NaN                                         NaN   
276729                       NaN                                         NaN   
276736                       NaN                                         NaN   
276737                       NaN                                         NaN   
276744                       NaN                                         NaN   
276745                       NaN                                         NaN   
276747                       NaN                                         NaN   
276748                       NaN                                         NaN   
276751                       NaN                                         NaN   
276754                       NaN                                         NaN   

Book.Title   Repairing PC Drives &amp  '48  \
276726                            NaN  NaN   
276729                            NaN  NaN   
276736                            NaN  NaN   
276737                            NaN  NaN   
276744                            NaN  NaN   
276745                            NaN  NaN   
276747                            NaN  NaN   
276748                            NaN  NaN   
276751                            NaN  NaN   
276754                            NaN  NaN   

Book.Title  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
276726                                                    NaN                       
276729                                                    NaN                       
276736                                                    NaN                       
276737                                                    NaN                       
276744                                                    NaN                       
276745                                                    NaN                       
276747                                                    NaN                       
276748                                                    NaN                       
276751                                                    NaN                       
276754                                                    NaN                       

Book.Title  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
276726                                                    NaN              
276729                                                    NaN              
276736                                                    NaN              
276737                                                    NaN              
276744                                                    NaN              
276745                                                    NaN              
276747                                                    NaN              
276748                                                    NaN              
276751                                                    NaN              
276754                                                    NaN              

Book.Title  01-01-00: A Novel of the Millennium  \
276726                                      NaN   
276729                                      NaN   
276736                                      NaN   
276737                                      NaN   
276744                                      NaN   
276745                                      NaN   
276747                                      NaN   
276748                                      NaN   
276751                                      NaN   
276754                                      NaN   

Book.Title  1,401 More Things That P*Ss Me Off  10 Commandments Of Dating  \
276726                                     NaN                        NaN   
276729                                     NaN                        NaN   
276736                                     NaN

In [16]:
user_user_recommendation.fillna(value=0,axis=0,inplace=True)
user_user_recommendation.head(10)

Book.Title   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
276726                       0.0                                         0.0   
276729                       0.0                                         0.0   
276736                       0.0                                         0.0   
276737                       0.0                                         0.0   
276744                       0.0                                         0.0   
276745                       0.0                                         0.0   
276747                       0.0                                         0.0   
276748                       0.0                                         0.0   
276751                       0.0                                         0.0   
276754                       0.0                                         0.0   

Book.Title   Repairing PC Drives &amp  '48  \
276726                            0.0  0.0   
276729                            0.0  0.0   
276736                            0.0  0.0   
276737                            0.0  0.0   
276744                            0.0  0.0   
276745                            0.0  0.0   
276747                            0.0  0.0   
276748                            0.0  0.0   
276751                            0.0  0.0   
276754                            0.0  0.0   

Book.Title  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
276726                                                    0.0                       
276729                                                    0.0                       
276736                                                    0.0                       
276737                                                    0.0                       
276744                                                    0.0                       
276745                                                    0.0                       
276747                                                    0.0                       
276748                                                    0.0                       
276751                                                    0.0                       
276754                                                    0.0                       

Book.Title  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
276726                                                    0.0              
276729                                                    0.0              
276736                                                    0.0              
276737                                                    0.0              
276744                                                    0.0              
276745                                                    0.0              
276747                                                    0.0              
276748                                                    0.0              
276751                                                    0.0              
276754                                                    0.0              

Book.Title  01-01-00: A Novel of the Millennium  \
276726                                      0.0   
276729                                      0.0   
276736                                      0.0   
276737                                      0.0   
276744                                      0.0   
276745                                      0.0   
276747                                      0.0   
276748                                      0.0   
276751                                      0.0   
276754                                      0.0   

Book.Title  1,401 More Things That P*Ss Me Off  10 Commandments Of Dating  \
276726                                     0.0                        0.0   
276729                                     0.0                        0.0   
276736                                     0.0

In [17]:
user_user_recommendation.dtypes

Book.Title
 Jason, Madison &amp                                                       float64
 Other Stories;Merril;1985;McClelland &amp                                 float64
 Repairing PC Drives &amp                                                  float64
'48                                                                        float64
'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities      float64
                                                                            ...   
\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character    float64
\Well, there's your problem\: Cartoons                                     float64
iI Paradiso Degli Orchi                                                    float64
stardust                                                                   float64
�?�?bermorgen.                                                             float64
Length: 9659, dtype: object

## Model Building and identifying the similar users for recommendation 

In [18]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import correlation,cosine

In [19]:
user_user_recommendation.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 7., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
## to get similarity score between 0 to 1, we can use another metrics called as cosine 
user_user_similarity = 1- pairwise_distances(X=user_user_recommendation.values,metric='cosine') 
user_user_similarity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [21]:
user_user_df = pd.DataFrame(user_user_similarity)
user_user_df.head()

0     1     2     3     4     5     6     7     8     9     ...  2172  \
0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

   2173  2174  2175  2176  2177  2178  2179  2180  2181  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 2182 columns]

In [22]:
# to make the similarity score of user correlating with itself to 0 
np.fill_diagonal(user_user_similarity, 0)

##### Finding the similarity between the users based on the ratings

In [24]:
user_user_df.shape

(2182, 2182)

In [25]:
user_user_df.idxmax(axis=1).head(15)

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7     2059
8        0
9        0
10       0
11       0
12       0
13       0
14    1031
dtype: int64

### We could see that there is a similarity between the user 7 and 2059 and also 14 and 1031

In [29]:
data1[(data1['User.ID']==14) | (data1['User.ID']==1031)]

User.ID                            Book.Title  Book.Rating
2409       14                                  COPS            5
2410       14  A Cold Heart: An Alex Delaware Novel            5
2411       14                            Dead Sleep            6
3616     1031                    Drawn to the Grave            7
3617     1031                         Viaduct Child            7

In [31]:
user1 = data1[(data1['User.ID'])==14]
user1

User.ID                            Book.Title  Book.Rating
2409       14                                  COPS            5
2410       14  A Cold Heart: An Alex Delaware Novel            5
2411       14                            Dead Sleep            6

In [32]:
user2 = data1[(data1['User.ID'])==1031]
user2

User.ID          Book.Title  Book.Rating
3616     1031  Drawn to the Grave            7
3617     1031       Viaduct Child            7

#### We can recommend the books read by the user 14 (COPS, A Cold Heart: An Alex Delaware Novel,Dead Sleep )to user 1031